language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 3.5
      dist: xenial
      sudo: required
      env: TOXENV=py35-django21-drf39

    - python: 3.6
      dist: xenial
      sudo: required
      env: TOXENV=py36-django21-drf39

    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37-django21-drf39

install:
  - pip install tox

script:
    - tox